===== Sample #1 Input =====
8
try
    try
        throw ( AE ) 
    catch ( BE, &quot;BE in line 3&quot;)

    try
    catch(AE, &quot;AE in line 5&quot;) 
catch(AE,&quot;AE somewhere&quot;)

===== Sample #1 Output =====
AE somewhere

===== Sample #2 Input =====
8
try
    try
        throw ( AE ) 
    catch ( AE, &quot;AE in line 3&quot;)

    try
    catch(BE, &quot;BE in line 5&quot;) 
catch(AE,&quot;AE somewhere&quot;)

===== Sample #2 Output =====
AE in line 3

===== Sample #3 Input =====
8
try
    try
        throw ( CE ) 
    catch ( BE, &quot;BE in line 3&quot;)

    try
    catch(AE, &quot;AE in line 5&quot;) 
catch(AE,&quot;AE somewhere&quot;)

===== Sample #3 Output =====
Unhandled Exception

